disallowed-methods = [
    # Shouldn't need to access these directly
    "voxly_database::models::bots::model::Bot::remove_field",
    "voxly_database::models::messages::model::Message::attach_sendable_embed",
    "voxly_database::models::users::model::User::set_relationship",
    "voxly_database::models::users::model::User::apply_relationship",

    # Prefer to use Object::create()
    "voxly_database::models::bots::ops::AbstractBots::insert_bot",
    "voxly_database::models::channel_invites::ops::AbstractChannelInvites::insert_invite",
    "voxly_database::models::channel_unreads::ops::AbstractChannelUnreads::acknowledge_message",
    "voxly_database::models::channel_webhooks::ops::AbstractWebhooks::insert_webhook",
    "voxly_database::models::channels::ops::AbstractChannels::insert_channel",
    "voxly_database::models::emojis::ops::AbstractEmojis::insert_emoji",
    "voxly_database::models::files::ops::AbstractAttachments::insert_attachment",
    "voxly_database::models::messages::ops::AbstractMessages::insert_message",
    "voxly_database::models::ratelimit_events::ops::AbstractRatelimitEvents::insert_ratelimit_event",
    "voxly_database::models::server_bans::ops::AbstractServerBans::insert_ban",
    "voxly_database::models::server_members::ops::AbstractServerMembers::insert_member",
    "voxly_database::models::servers::ops::AbstractServers::insert_server",
    "voxly_database::models::users::ops::AbstractUsers::insert_user",

    # Prefer to use Object::update(&self)
    "voxly_database::models::bots::ops::AbstractBots::update_bot",

    # Prefer to use Object::delete(&self)
    "voxly_database::models::bots::ops::AbstractBots::delete_bot",
]
