[package]
name = "voxly-parser"
version = "0.11.5"
edition = "2021"
license = "MIT"
authors = ["Zomatree <me@zomatree.live>", "Paul Makles <me@insrt.uk>"]
description = "Voxly Backend: Message Parser"
repository = "https://github.com/voxly-gg/stoatchat"

[dependencies]
logos = { version = "0.15" }
